import { Cell } from "../JSChessEngine";

export const INITIAL_CELLS: Cell[][] = [
    [
      { figure: { type: 'rook', color: 'black', touched: false } },
      { figure: { type: 'knigts', color: 'black', touched: false } },
      { figure: { type: 'bishop', color: 'black', touched: false } },
      { figure: { type: 'queen', color: 'black', touched: false } },
      { figure: { type: 'king', color: 'black', touched: false } },
      { figure: { type: 'bishop', color: 'black', touched: false } },
      { figure: { type: 'knigts', color: 'black', touched: false } },
      { figure: { type: 'rook', color: 'black', touched: false } },
    ],
    [
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
    ],
    [
      { figure: { type: 'rook', color: 'white', touched: false } },
      { figure: { type: 'knigts', color: 'white', touched: false } },
      { figure: { type: 'bishop', color: 'white', touched: false } },
      { figure: { type: 'queen', color: 'white', touched: false } },
      { figure: { type: 'king', color: 'white', touched: false } },
      { figure: { type: 'bishop', color: 'white', touched: false } },
      { figure: { type: 'knigts', color: 'white', touched: false } },
      { figure: { type: 'rook', color: 'white', touched: false } },
    ],
  ];

export const STATE_CELLS_WITHOUT_LONG_CASTLINGS: Cell[][] = [
    [
      { figure: undefined },
      { figure: { type: 'rook', color: 'black', touched: true } },
      { figure: { type: 'bishop', color: 'black', touched: false } },
      { figure: { type: 'queen', color: 'black', touched: false } },
      { figure: { type: 'king', color: 'black', touched: false } },
      { figure: { type: 'bishop', color: 'black', touched: false } },
      { figure: undefined },
      { figure: { type: 'rook', color: 'black', touched: false } },
    ],
    [
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: { type: 'pawn', color: 'black', touched: false } },
      { figure: undefined },
      { figure: { type: 'pawn', color: 'black', touched: false } },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: { type: 'knigts', color: 'black', touched: false } },
      { figure: undefined },
      { figure: undefined },
      { figure: { type: 'knigts', color: 'black', touched: true } },
      { figure: { type: 'pawn', color: 'black', touched: true } },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
      { figure: undefined },
    ],
    [
      { figure: undefined },
      { figure: undefined },
      { figure: { type: 'knigts', color: 'white', touched: true } },
      { figure: undefined },
      { figure: undefined },
      { figure: { type: 'pawn', color: 'white', touched: true } },
      { figure: { type: 'pawn', color: 'white', touched: true } },
      { figure: undefined },
    ],
    [
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: { type: 'pawn', color: 'white', touched: false } },
      { figure: undefined },
      { figure: undefined },
      { figure: { type: 'pawn', color: 'white', touched: false } },
    ],
    [
      { figure: undefined },
      { figure: { type: 'rook', color: 'white', touched: true } },
      { figure: { type: 'bishop', color: 'white', touched: false } },
      { figure: { type: 'queen', color: 'white', touched: false } },
      { figure: { type: 'king', color: 'white', touched: false } },
      { figure: { type: 'bishop', color: 'white', touched: false } },
      { figure: { type: 'knigts', color: 'white', touched: false } },
      { figure: { type: 'rook', color: 'white', touched: false } },
    ],
  ];